### PR TITLE
Fix finding the binary on Apple Silicon machines

### PR DESCRIPTION
**Pull request by michaelherger**
Don't add the arch postfix to the folder name. That should allow to use the existing x86_64 dsdplay using Rosetta.

A future change should add an arm64 branch to build a universal binary.

### CODE REVIEW

**Comment by terual** [comment]
Thanks! I have also updated the repo.xml and created a new zip release so this change will be picked up.

BTW, any idea how to build a new binary for Apple silicon? Will you need an Apple M1 or would cross-compiling work?

**Comment by michaelherger** [comment]
I believe you should be able to cross-compile. @philippe44 even compiles for both macOS platforms on Linux... I gave it a quick try on my M1, but it failed, lack of some header file (`stdio.h`). Lack of experience cross compiling I gave up quickly. But if you can give me some hint I might give it another try.

**Comment by terual** [comment]
Did you try to use the "Makefile.macos"? (And replace both occurences of "-arch x86_64" in the Makefile with "-arch armv8-a"). If that fails I will try to cross-compile.

**Comment by michaelherger** [comment]
I replaced with arm64. And bumped the framework version etc. Then I got blocked on some missing FLAC header files.

```
 % make -f Makefile.macos    
cc -c -o build/dsdplay.o dsdplay.c -O3 -Wstrict-prototypes -I./include64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -arch arm64 -mmacosx-version-min=11.0
dsdplay.c:31:10: fatal error: 'FLAC/stream_encoder.h' file not found
#include <FLAC/stream_encoder.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/dsdplay.o] Error 1
```

**Comment by terual** [comment]
It seems that the flac development library is not installed, but I have no idea what the equivalent would be to libflac-dev (debian) or flac-devel (redhat) in macOS world. Doesn't `brew` do this?

**Comment by michaelherger** [comment]
The binary can be installed using `brew`. But I didn't see a dev or headers package. I guess I'd have to download the Flac tarball and point it at that.

**Comment by terual** [comment]
Same with soxr then, both flac and soxr are needed to build dsdplay.

**Comment by ralph-irving** [comment]
Thanks for fixing the plugin.  I should be able to add M1 support to the dsdplay binary if you'd like.

**Pull request merged**
